### ISSUE TITLE
Add support for plugins actions

### ISSUE THREAD

**Issue by arhubi** [BretCameron/strapi-plugin-public-permissions#2]
Hi @BretCameron, 
First of all, thank you for this amazing plugin! It's really useful and save me a lot of time and headaches. 🙏 

I have a feature request : as of now, you handle the `api` routes (contentTypes), but in my company case, we would want to give access to `plugin` too.
Do you think it's possible to add it as a plugin feature?

Some examples of our app needs: 
- `listLocales` from i18n plugin, to define the enabled locales in our app
- `find` from [redirects plugin
](https://github.com/Webbist-dev/strapi-redirects) to handle in-app redirections.

If you don't have the time or inclination to implement this feature, could you help me a bit so that I could open a PR?

Thank you very much!

**Comment by BretCameron** [comment]
Thank you for the feature suggestion!

I think we could add a separate config argument for `plugins`, since I don't think they'll play nicely with the wildcard feature we have for API actions.

I will look into this in the coming week.

**Comment by BretCameron** [comment]
The `plugins` configuration option has been added in [v0.2.0](https://github.com/BretCameron/strapi-plugin-public-permissions/releases/tag/v0.2.0).

I hope this is useful!

**Comment by arhubi** [comment]
Thank you very much, really appreciated!
